version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - ml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '5000:5000'
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

  ml:
    image: python:3.8
    working_dir: /usr/src/app
    volumes:
      - ./ml:/usr/src/app/ml
      - ./data:/usr/src/app/data
    command: python /usr/src/app/ml/process.py
    depends_on:
      - backend
